#create workflow for salesforce login
name: Login salesforce to test

#workflow triggerd by push request
on: [push]

jobs:
  my_first_jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Salesforce CLI
        run: |
          curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz --output sfdx.tar.xz
          mkdir sfdx
          tar xJf sfdx.tar.xz -C sfdx --strip-components 1
          sudo ./sfdx/install
          
      - name: Authenticate with Salesforce CLI
        run: |
         sfdx force:auth:web:login --setalias MyOrgAlias --instanceurl https://login.salesforce.com --setdefaultusername

