name: Login to Salesforce
on:
  push:
    branches:
      - main
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Salesforce
        uses: salesforce/sfdx-cli-action@v1
        with:
          sfdx-auth-url: ${{ secrets.SFDC_AUTH_URL }}
